[package]
name = "vfs"
version = "0.9.0"
authors = ["Manuel Woelker <github@manuel.woelker.org>"]
description = "A virtual filesystem for Rust"
repository = "https://github.com/manuel-woelker/rust-vfs"
readme = "README.md"
keywords = ["vfs", "virtual",  "filesystem"]
license = "Apache-2.0"
edition = "2018"

[badges]
travis-ci = { repository = "manuel-woelker/rust-vfs", branch = "master" }

[dependencies]
rust-embed = { version = "6.3.*", optional = true }
rust-embed-impl = { version = "6.2.*", optional = true }
serde = { version = "1.0.*", features = ["derive"], optional = true }

[dev-dependencies]
uuid = { version = "=0.8.1", features = ["v4"] }
camino = "1.0.5"
anyhow = "1.0.58"

[features]
embedded-fs = ["rust-embed", "rust-embed-impl"]
export-test-macros = []
serde = ["dep:serde"]

[package.metadata.docs.rs]
features = ["embedded-fs", "serde"]
